"""Add filtering fields to posts table

Revision ID: 2c253f46f848
Revises: e71c887d2ca6
Create Date: 2025-07-12 22:27:33.083710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c253f46f848'
down_revision = 'e71c887d2ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('allow_comments', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'allow_comments')
    op.drop_column('posts', 'is_public')
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'category')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
