"""Extend profile fields

Revision ID: 4f371db8ee77
Revises: d7c442ec96d9
Create Date: 2025-07-04 16:16:14.499582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f371db8ee77'
down_revision = 'd7c442ec96d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('twitter')
        batch_op.drop_column('github')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('website')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
