"""Add comments table

Revision ID: e71c887d2ca6
Revises: f56a5b3ec27d
Create Date: 2025-07-11 15:09:11.398757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71c887d2ca6'
down_revision = 'f56a5b3ec27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
