"""Add media_url to posts table

Revision ID: f56a5b3ec27d
Revises: 65eaa8e1e682
Create Date: 2025-07-11 13:58:06.546557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56a5b3ec27d'
down_revision = '65eaa8e1e682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_url')
    # ### end Alembic commands ###
